eureka:
  instance:
    #实例ID，可用于注册中心界面展示注册机器基本信息
    instanceId: ${spring.application.name}-${spring.cloud.client.ipAddress}-${server.port}
    #注册中心端默认多少秒没有收到client端心跳就认为client失效了，失效后会将对应client从注册中心移除
    leaseExpirationDurationInSeconds: 15
    #心跳间隔，即多少秒就向注册中心发送心跳
    leaseRenewalIntervalInSeconds: 5
  client:
    healthcheck:
      #开启健康检查
      enabled: true
    #客户端每隔多少秒就需要重新拉取一次注册中心配置
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://regcentera:6601/eureka/,http://regcenterb:6602/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 500 #缺省为10
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 50 ## 当在配置时间窗口内达到此数量的失败后，进行短路。默认20个
        sleepWindowInMilliseconds: 3 ## 短路多久以后开始尝试是否恢复，默认5s
      fallback:
        isolation:
          semaphore:
            maxConcurrentReques: 500 ##熔断线程池大小
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 ##单个请求熔断超时时间10s